version: '3'

services:
  esdb-node:
    image: eventstore/eventstore:lts
    container_name: esdb-node
    ports:
      - "2113:2113"
      - "1113:1113"
    command: >
      --insecure
      --run-projections=All
      --enable-external-tcp
      --enable-atom-pub-over-http

  mongodb:
    container_name: mamad_mongo
    image: mongo
    ports:
      - "27017:27017"

  spring-app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - backend
    container_name: app_backend
    depends_on:
      - mongodb
      - esdb-node

networks:
  backend:
    driver: bridge
