spring:
  data:
    mongodb:
      projection:
        database: projection
      local:
          database: beneficiary
      uri: mongodb://192.168.18.59:27017


spring.autoconfigure.exclude: |
  org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration,
  org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration,
  org.springframework.boot.autoconfigure.data.mongo.MongoReactiveDataAutoConfiguration,
  org.springframework.boot.autoconfigure.data.mongo.MongoReactiveRepositoriesAutoConfiguration,
  org.springframework.boot.autoconfigure.data.mongo.MongoRepositoriesAutoConfiguration

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG



esdb:
  connectionstring: esdb://192.168.18.59:2113?tls=false