spring:

  profiles:
    active: ${ACTIVE_PROFILE:dev}

  data:
    mongodb:
      projection:
        database: projection
      local:
          database: beneficiary
      host: mamad_mongo
      port: 27017


  autoconfigure:
    exclude: |
        org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration,
        org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration,
        org.springframework.boot.autoconfigure.data.mongo.MongoReactiveDataAutoConfiguration,
        org.s pringframework.boot.autoconfigure.data.mongo.MongoReactiveRepositoriesAutoConfiguration,
        org.springframework.boot.autoconfigure.data.mongo.MongoRepositoriesAutoConfiguration


esdb:
  connectionstring: esdb-node
  port: 2113

