spring:
  data:
    mongodb:
      uri: mongodb://192.168.18.106:27017/diba_read

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG


esdb:
  connectionstring: esdb://http://192.168.18.106:2113?tls=false