spring:
  data:
    mongodb:
      uri: mongodb://192.168.19.148:27017/diba_read

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG


esdb:
  connectionstring: esdb://192.168.19.148:2113?tls=false